<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath/>
	</parent>

	<groupId>com.pauluno</groupId>
	<artifactId>finledger-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>FinLedger Parent</name>
	<description>Parent reactor for FinLedger server and CLI</description>
	<url>https://github.com/PaulUno777/finledger</url>

	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
	<developers>
		<developer>
			<id>PaulUno777</id>
			<name>Paulin NZODOUM</name>
			<url>https://github.com/PaulUno777</url>
		</developer>
	</developers>
	<scm>
		<connection>scm:git:https://github.com/PaulUno777/finledger.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/PaulUno777/finledger.git</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/PaulUno777/finledger</url>
	</scm>

	<modules>
		<module>finledger-security-policy</module>
		<module>finledger</module>
		<module>finledger-cli</module>
	</modules>

	<properties>
		<java.version>21</java.version>
		<picocli.version>4.7.7</picocli.version>
		<jline.version>3.30.4</jline.version>
	</properties>
</project>
