package com.pauluno.finledger.cli.command;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.concurrent.Callable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.pauluno.finledger.security.policy.RuntimeSecurityPolicy;
import com.pauluno.finledger.security.policy.RuntimeSecurityViolationException;

import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

/**
 * Local YAML config authoring (profile + issuer — ADR-016).
 */
@Command(name = "config", description = "Author local FinLedger config (YAML only; no HTTP)", subcommands = {
        ConfigInitCommand.class,
        ConfigSetCommand.class,
        ConfigValidateCommand.class
})
public class ConfigCommand implements Runnable {
    @Override
    public void run() {
        System.out.println("Specify a subcommand (init|set|validate). Use --help for details.");
    }
}

@Command(name = "init", description = "Create a local config override file")
class ConfigInitCommand implements Callable<Integer> {

    @Option(names = "--profile", description = "sandbox | normal", defaultValue = "normal")
    String profile;

    @Option(names = "--issuer", description = "external | internal", defaultValue = "external")
    String issuer;

    @Option(names = "--out", description = "Output path", defaultValue = "./config/application.yml")
    Path out;

    @Option(names = "--env", description = "finledger.env value", defaultValue = "local")
    String env;

    @Override
    public Integer call() throws IOException {
        String normalizedIssuer = RuntimeSecurityPolicy.normalizeIssuer(issuer);
        String normalizedProfile = profile.trim().toLowerCase(Locale.ROOT);
        if (!"sandbox".equals(normalizedProfile) && !"normal".equals(normalizedProfile)) {
            System.err.println("Unknown --profile '" + profile + "' (expected sandbox|normal)");
            return 1;
        }
        if ("sandbox".equals(normalizedProfile)) {
            normalizedIssuer = "internal";
        }
        if (Files.exists(out)) {
            System.err.println("Refusing to overwrite existing file: " + out.toAbsolutePath());
            return 1;
        }
        Path parent = out.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        String yaml = """
                # Generated by finledger-cli config init (ADR-016)
                # Mount or place under spring.config.additional-location (./config/).
                # Also set SPRING_PROFILES_ACTIVE=%s in the environment / Compose.
                spring:
                  profiles:
                    active: %s
                finledger:
                  env: %s
                  security:
                    issuer: %s
                """.formatted(normalizedProfile, normalizedProfile, env, normalizedIssuer);
        Files.writeString(out, yaml, StandardCharsets.UTF_8);
        System.out.println("Wrote " + out.toAbsolutePath());
        ConfigRestartHints.printToStdout();
        return 0;
    }
}

@Command(name = "set", description = "Patch a key in a local config file")
class ConfigSetCommand implements Callable<Integer> {

    @Option(names = "--file", description = "Config file to patch", defaultValue = "./config/application.yml")
    Path file;

    @Parameters(index = "0", description = "Key: security.issuer | env | profile")
    String key;

    @Parameters(index = "1", description = "Value")
    String value;

    @Override
    public Integer call() throws IOException {
        if (!Files.isRegularFile(file)) {
            System.err.println("File not found: " + file + " (run config init first)");
            return 1;
        }
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String normalizedKey = key.trim().toLowerCase(Locale.ROOT);
        String updated = switch (normalizedKey) {
            case "security.issuer", "finledger.security.issuer", "issuer" -> {
                String issuer = RuntimeSecurityPolicy.normalizeIssuer(value);
                yield upsertIndented(content, "issuer", issuer, 4);
            }
            case "env", "finledger.env" -> upsertIndented(content, "env", value, 2);
            case "profile", "spring.profiles.active" -> {
                String profile = value.trim().toLowerCase(Locale.ROOT);
                if (!"sandbox".equals(profile) && !"normal".equals(profile)) {
                    throw new IllegalArgumentException(
                            "Unknown profile '" + value + "' (expected sandbox|normal)");
                }
                yield upsertIndented(content, "active", profile, 4);
            }
            default -> throw new IllegalArgumentException(
                    "Unsupported key '" + key + "' (use security.issuer|env|profile)");
        };
        Files.writeString(file, updated, StandardCharsets.UTF_8);
        System.out.println("Updated " + file.toAbsolutePath());
        ConfigRestartHints.printToStdout();
        return 0;
    }

    static String upsertIndented(String content, String key, String value, int indentSpaces) {
        String indent = " ".repeat(indentSpaces);
        Pattern pattern = Pattern.compile(
                "(?m)^" + Pattern.quote(indent) + Pattern.quote(key) + "\\s*:.*$");
        Matcher matcher = pattern.matcher(content);
        String line = indent + key + ": " + value;
        if (matcher.find()) {
            return matcher.replaceFirst(Matcher.quoteReplacement(line));
        }
        if ("env".equals(key)) {
            if (content.contains("finledger:")) {
                return content.replaceFirst("(?m)^(finledger:\\s*)$", "$1\n" + line);
            }
            return content + "\nfinledger:\n" + line + "\n";
        }
        if ("active".equals(key)) {
            if (content.contains("profiles:")) {
                return content.replaceFirst("(?m)^( {2}profiles:\\s*)$", "$1\n" + line);
            }
            if (content.contains("spring:")) {
                return content.replaceFirst("(?m)^(spring:\\s*)$", "$1\n  profiles:\n" + line);
            }
            return content + "\nspring:\n  profiles:\n" + line + "\n";
        }
        if (content.matches("(?s).*\\n {2}security:\\s*\\n.*") || content.contains("\n  security:\n")) {
            return content.replaceFirst("(?m)^( {2}security:\\s*)$", "$1\n" + line);
        }
        if (content.contains("finledger:")) {
            return content.replaceFirst("(?m)^(finledger:\\s*)$", "$1\n  security:\n" + line);
        }
        return content + "\nfinledger:\n  security:\n" + line + "\n";
    }
}

@Command(name = "validate", description = "Validate sandbox/production interlock")
class ConfigValidateCommand implements Callable<Integer> {

    @Option(names = "--file", description = "Config file", defaultValue = "./config/application.yml")
    Path file;

    @Option(names = "--profiles", description = "Comma-separated spring profiles to assume", defaultValue = "")
    String profiles;

    @Override
    public Integer call() throws IOException {
        if (!Files.isRegularFile(file)) {
            System.err.println("File not found: " + file);
            return 1;
        }
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String env = extractScalar(content, "env").orElse("local");
        String issuerRaw = extractScalar(content, "issuer").orElse("external");
        String profileFromFile = extractScalar(content, "active").orElse("");
        String issuer;
        try {
            issuer = RuntimeSecurityPolicy.normalizeIssuer(issuerRaw);
        } catch (IllegalArgumentException ex) {
            System.err.println(ex.getMessage());
            return 1;
        }
        String effectiveProfiles = profiles.isBlank() ? profileFromFile : profiles;
        String[] profileList = effectiveProfiles.isBlank() ? new String[0] : effectiveProfiles.split(",");
        try {
            RuntimeSecurityPolicy.assertProfilesExclusive(java.util.Arrays.asList(profileList));
            RuntimeSecurityPolicy.assertSandboxProfileAllowed(env, profileList);
        } catch (RuntimeSecurityViolationException ex) {
            System.err.println("INVALID: " + ex.getMessage());
            return 1;
        }
        System.out.println("OK: issuer=" + issuer + " env=" + env
                + (effectiveProfiles.isBlank() ? "" : " profiles=" + effectiveProfiles));
        ConfigRestartHints.printToStdout();
        return 0;
    }

    private static java.util.Optional<String> extractScalar(String yaml, String key) {
        Pattern pattern = Pattern.compile("(?m)^\\s*" + Pattern.quote(key) + "\\s*:\\s*(.+?)\\s*$");
        Matcher matcher = pattern.matcher(yaml);
        if (!matcher.find()) {
            return java.util.Optional.empty();
        }
        String raw = matcher.group(1).trim();
        if ((raw.startsWith("\"") && raw.endsWith("\"")) || (raw.startsWith("'") && raw.endsWith("'"))) {
            raw = raw.substring(1, raw.length() - 1);
        }
        return java.util.Optional.of(raw);
    }
}
