package com.pauluno.finledger.cli.command;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.concurrent.Callable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.pauluno.finledger.security.policy.SecurityMode;
import com.pauluno.finledger.security.policy.SecurityModePolicy;
import com.pauluno.finledger.security.policy.SecurityModeViolationException;

import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

/**
 * Local YAML config authoring only (FL-151) — never HTTP.
 */
@Command(
        name = "config",
        description = "Author local FinLedger config (YAML only; no HTTP)",
        subcommands = {
                ConfigInitCommand.class,
                ConfigSetCommand.class,
                ConfigValidateCommand.class
        }
)
public class ConfigCommand implements Runnable {
    @Override
    public void run() {
        System.out.println("Specify a subcommand (init|set|validate). Use --help for details.");
    }
}

@Command(name = "init", description = "Create a local config override file")
class ConfigInitCommand implements Callable<Integer> {

    @Option(names = "--mode", description = "enforced | static-token | disabled", defaultValue = "disabled")
    String mode;

    @Option(names = "--out", description = "Output path", defaultValue = "./config/application.yml")
    Path out;

    @Option(names = "--env", description = "finledger.env value", defaultValue = "local")
    String env;

    @Override
    public Integer call() throws IOException {
        SecurityMode parsed = SecurityMode.parse(mode);
        if (Files.exists(out)) {
            System.err.println("Refusing to overwrite existing file: " + out.toAbsolutePath());
            return 1;
        }
        Path parent = out.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        String yaml = """
                # Generated by finledger-cli config init (FL-151)
                # Mount or place under spring.config.additional-location (./config/).
                finledger:
                  env: %s
                  security:
                    mode: %s
                """.formatted(env, parsed.configValue());
        Files.writeString(out, yaml, StandardCharsets.UTF_8);
        System.out.println("Wrote " + out.toAbsolutePath());
        return 0;
    }
}

@Command(name = "set", description = "Patch a key in a local config file")
class ConfigSetCommand implements Callable<Integer> {

    @Option(names = "--file", description = "Config file to patch", defaultValue = "./config/application.yml")
    Path file;

    @Parameters(index = "0", description = "Key: security.mode | security.static-token | env")
    String key;

    @Parameters(index = "1", description = "Value")
    String value;

    @Override
    public Integer call() throws IOException {
        if (!Files.isRegularFile(file)) {
            System.err.println("File not found: " + file + " (run config init first)");
            return 1;
        }
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String normalizedKey = key.trim().toLowerCase(Locale.ROOT);
        String updated = switch (normalizedKey) {
            case "security.mode", "finledger.security.mode", "mode" -> {
                SecurityMode mode = SecurityMode.parse(value);
                yield upsertIndented(content, "mode", mode.configValue(), 4);
            }
            case "security.static-token", "finledger.security.static-token", "static-token" ->
                    upsertIndented(content, "static-token", value, 4);
            case "env", "finledger.env" -> upsertIndented(content, "env", value, 2);
            default -> throw new IllegalArgumentException(
                    "Unsupported key '" + key + "' (use security.mode|security.static-token|env)");
        };
        Files.writeString(file, updated, StandardCharsets.UTF_8);
        System.out.println("Updated " + file.toAbsolutePath());
        return 0;
    }

    /**
     * Upserts {@code key: value} at the given indentation under a finledger tree.
     */
    static String upsertIndented(String content, String key, String value, int indentSpaces) {
        String indent = " ".repeat(indentSpaces);
        Pattern pattern = Pattern.compile(
                "(?m)^" + Pattern.quote(indent) + Pattern.quote(key) + "\\s*:.*$");
        Matcher matcher = pattern.matcher(content);
        String line = indent + key + ": " + value;
        if (matcher.find()) {
            return matcher.replaceFirst(Matcher.quoteReplacement(line));
        }
        if ("env".equals(key)) {
            if (content.contains("finledger:")) {
                return content.replaceFirst("(?m)^(finledger:\\s*)$", "$1\n" + line);
            }
            return content + "\nfinledger:\n" + line + "\n";
        }
        // security.* keys — ensure security: block exists
        if (content.matches("(?s).*\\n {2}security:\\s*\\n.*") || content.contains("\n  security:\n")) {
            return content.replaceFirst("(?m)^( {2}security:\\s*)$", "$1\n" + line);
        }
        if (content.contains("finledger:")) {
            return content.replaceFirst("(?m)^(finledger:\\s*)$", "$1\n  security:\n" + line);
        }
        return content + "\nfinledger:\n  security:\n" + line + "\n";
    }
}

@Command(name = "validate", description = "Validate local security mode against production interlock")
class ConfigValidateCommand implements Callable<Integer> {

    @Option(names = "--file", description = "Config file", defaultValue = "./config/application.yml")
    Path file;

    @Option(names = "--profiles", description = "Comma-separated spring profiles to assume", defaultValue = "")
    String profiles;

    @Override
    public Integer call() throws IOException {
        if (!Files.isRegularFile(file)) {
            System.err.println("File not found: " + file);
            return 1;
        }
        String content = Files.readString(file, StandardCharsets.UTF_8);
        String modeRaw = extractScalar(content, "mode").orElse("enforced");
        String env = extractScalar(content, "env").orElse("local");
        String staticToken = extractScalar(content, "static-token").orElse("");
        SecurityMode mode;
        try {
            mode = SecurityMode.parse(modeRaw);
        } catch (IllegalArgumentException ex) {
            System.err.println(ex.getMessage());
            return 1;
        }
        try {
            SecurityModePolicy.assertBootAllowed(mode, env, profiles.split(","));
        } catch (SecurityModeViolationException ex) {
            System.err.println("INVALID: " + ex.getMessage());
            return 1;
        }
        System.out.println("OK: mode=" + mode.configValue() + " env=" + env
                + (profiles.isBlank() ? "" : " profiles=" + profiles));
        if (mode == SecurityMode.STATIC_TOKEN && (staticToken == null || staticToken.isBlank())) {
            System.out.println("WARN: static-token empty in file — set FINLEDGER_STATIC_TOKEN (or config set security.static-token …)");
        }
        return 0;
    }

    private static java.util.Optional<String> extractScalar(String yaml, String key) {
        Pattern pattern = Pattern.compile("(?m)^\\s*" + Pattern.quote(key) + "\\s*:\\s*(.+?)\\s*$");
        Matcher matcher = pattern.matcher(yaml);
        if (!matcher.find()) {
            return java.util.Optional.empty();
        }
        String raw = matcher.group(1).trim();
        if ((raw.startsWith("\"") && raw.endsWith("\"")) || (raw.startsWith("'") && raw.endsWith("'"))) {
            raw = raw.substring(1, raw.length() - 1);
        }
        return java.util.Optional.of(raw);
    }
}
